@startuml

title WarmHome Container Diagram

top to bottom direction

!include ./C4_Container.puml

Person(user, "Пользователь", "Пользователь warmhouse system")
Person(support, "Пользователи службы поддержки", "Операторы и специалисты техподдержки WarmHouse")
System(WarmHouseSystem, "Система Теплый дом", "Система управление умными устройствами")

Container_Boundary(WarmHouseSystem, "Система Теплый дом") {
    Container(AuthService, "Auth Service", "Python, FastAPI", "Аутентификация, выпуск и проверка JWT")
    Container(UserService, "User Service", "Python, FastAPI", "Управление пользователями и домами")
    Container(SensorService, "Сервис умных устройств", "Python, FastAPI", "Логика управления умными устройствами")
    ContainerDb(UserDatabase, "UserDatabase", "PostgreSQL", "Хранение данных пользователей")
    ContainerDb(SensorDatabase, "SensorDatabase", "ClickHouse", "Хранение данных умных устройств")
    ContainerDb(AuthDatabase, "AuthDatabase", "PostgreSQL", "Хранение данных аутентификации")
    Container(WebApp, "Web приложение", "TypeScript, Vue", "Предоставляет UI пользователям")
 }

Boundary(home, "Дома пользователей") {
    System_Ext(api, "API умных устройств", "Взаимодействие с умными устройствами")
 }

Rel(user, WebApp, "Пользуется системой")
BiRel(support, WebApp, "Обращения, поддержка пользователей")
BiRel(WebApp, AuthService,"Логин, получение JWT")
BiRel(UserService,UserDatabase,"Чтение/запись данных пользователей")
BiRel(WebApp, SensorService,"Управление данными умных устройств (проверка JWT через AuthService)")
BiRel(SensorService,SensorDatabase,"Чтение/запись данных умных устройств")
BiRel(UserService,SensorService,"Управление конфигурациями умных устройств (проверка JWT)")
BiRel(SensorService,api,"Управление умными устройствами")
BiRel(AuthService, UserService,"Проверка учётных данных и JWT")
BiRel(AuthService, SensorService,"Валидация JWT")
BiRel(WebApp, UserService, "Управление данными пользователя (JWT)")
BiRel(AuthService, AuthDatabase, "Чтение/запись данных аутентификации")

SHOW_LEGEND()
@enduml